const fs = require('fs')

fs.writeFileSync(
    `./.env.${process.env.NODE_ENV}`,
    `
CONTENTFUL_SPACE_ID=${process.env.CONTENTFUL_SPACE_ID}\n
CONTENTFUL_ACCESS_TOKEN=${process.env.CONTENTFUL_ACCESS_TOKEN}\n
FIREBASE_API_KEY=${process.env.FIREBASE_API_KEY}\n
FIREBASE_AUTH_DOMAIN=${process.env.FIREBASE_AUTH_DOMAIN}\n
FIREBASE_DATABASE_URL=${process.env.FIREBASE_DATABASE_URL}\n
FIREBASE_PROJECT_ID=${process.env.FIREBASE_PROJECT_ID}\n
FIREBASE_STORAGE_BUCKET=${process.env.FIREBASE_STORAGE_BUCKET}\n
FIREBASE_MESSAGING_SENDER_ID=${process.env.FIREBASE_MESSAGING_SENDER_ID}\n
FIREBASE_APP_ID=${process.env.FIREBASE_APP_ID}\n
MEASUREMENT_ID=${process.env.MEASUREMENT_ID}\n
GATSBY_RECAPTCHA_CODE=${process.env.GATSBY_RECAPTCHA_CODE}\n
`,
)
